[package]
name = "Hotel"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
rand = "0.8"
strum = "0.24.1"
strum_macros = "0.24.1"
regex = "0.1.0"
chrono = "0.4.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"